ftp:
  vsftpd: true
  proftpd: true
  pure-ftpd: true

web:
  apache2: true
  nginx: true
  lighttpd: true
  caddy: true
  openlitespeed: true
  h2o: true
  tomcat10: true

proxy:
  squid: true
  tinyproxy: true
  privoxy: true
  polipo: true
  3proxy: true
  dante-server: true
  shadowsocks-libev: true
  v2ray: true
  haproxy: true
  varnish: true
  envoy: true
  traefik: true

fileshare:
  samba: true

mail:
  postfix: true
  exim4: true
  sendmail: true

client_services:
  nis_client: true
  rsh_client: true
  talk_client: true
  ldap_client: true
  telnet_client: true
  ftp_client: true