BEETLE_SHELL_ROOT=/usr/local/bin/beetle_shell/audit

AUDIT_CATEGORY_ROOT=${BEETLE_SHELL_ROOT}
AUDIT_RECURSIVE=true
AUDIT_SCRIPT_PATTERN=*.sh
AUDIT_IGNORE_ROOT_FILES=true
AUDIT_SHELL="/usr/bin/env bash"
AUDIT_OUTPUT_TIMEOUT=5
AUDIT_EXECUTION_TIMEOUT=10
AUDIT_MAX_CONCURRENT=1


AUDIT_LOG_ENABLED=true
AUDIT_LOG_DIR=/var/log/beetle
AUDIT_LOG_LEVEL=info
